apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      initContainers:
      - name: copy-files
        image: tntjd5596/spring-petclinic-data-jdbc:k8s10
        command: ['sh', '-c', 'cp /app/build/libs/spring-petclinic-*.jar /logs/application.jar']
        volumeMounts:
        - name: log-volume
          mountPath: /logs/
      containers:
      - name: springboot-pod
        image: tntjd5596/spring-petclinic-data-jdbc:k8s10
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: log-volume
          mountPath: /app/build/libs/
      volumes:
      - name: log-volume
        hostPath:
          path: /logs/
